import { StyleSheet } from 'react-native';

export const getStyles = (isDarkTheme:boolean) =>
 StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: isDarkTheme ? '' : '#f5f5f5',
    padding: 16,
  },
  searchContainer: {
    flexDirection: 'row',
    marginTop: 10,
    marginBottom: 10,
  },
  searchInput: {
    flex: 1,
    height: 46,
    backgroundColor: isDarkTheme ? '#000' : '#fff',
    borderRadius: 8,
    paddingHorizontal: 15,
    fontSize: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  searchButton: {
    width: 46,
    height: 46,
    backgroundColor: isDarkTheme ? '#000' :'#0066cc',
    borderRadius: 8,
    marginLeft: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  locationButton: {
    flexDirection: 'row',
    backgroundColor: '#4CAF50',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 15,
    marginBottom: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  locationButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 8,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#555',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  errorText: {
    fontSize: 16,
    color: '#d32f2f',
    textAlign: 'center',
  },
  scrollViewContent: {
    paddingBottom: 20,
  },
  currentWeatherContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },

  currentDateTime: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 5,
},
  locationName: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#333',
    textAlign: 'center',
  },
  currentWeatherContent: {
    alignItems: 'center',
   
  },
  temperatureContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  temperature: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#333',
    marginLeft: 10,
  },
  weatherDescription: {
    fontSize: 18,
    color: '#666',
    textTransform: 'capitalize',
    marginBottom: 15,
  },
  weatherDetailsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginTop: 10,
  },
  weatherDetail: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 5,
  },
  weatherDetailText: {
    fontSize: 14,
    color: '#555',
    marginLeft: 5,
  },
  feelsLikeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 15,
  },
  feelsLikeText: {
    fontSize: 14,
    color: '#555',
    marginLeft: 5,
  },
  hourlyForecastContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    alignItems: 'center',
  },
  hourlyForecastList: {
    paddingVertical: 10,
  },
  hourlyItem: {
    alignItems: 'center',
    marginHorizontal: 12,
    width: 60,
  },
  hourlyTime: {
    fontSize: 14,
    color: '#333',
    marginBottom: 8,
  },
  hourlyTemp: {
    fontSize: 16,
    fontWeight: '500',
    color: '#333',
    marginTop: 6,
    marginBottom: 4,
  },
  precipContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  precipText: {
    fontSize: 12,
    color: '#1E90FF',
    marginLeft: 2,
  },
  toggleContainer: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  toggleButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    backgroundColor: '#e0e0e0',
    borderWidth: 1,
    borderColor: '#ccc',
  },
  toggleButtonActive: {
    backgroundColor: '#0066cc',
  },
  toggleButtonText: {
    fontSize: 16,
    color: '#333',
  },
  toggleButtonTextActive: {
    color: '#fff',
    fontWeight: '500',
  },
  forecastContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  forecastTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 15,
    color: '#333',
  },
  forecastItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  forecastDay: {
    fontSize: 16,
    color: '#333',
    width: '30%',
  },
  forecastDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '68%',
  },
  forecastIconTemp: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  forecastTempContainer: {
    marginLeft: 8,
  },
  forecastTemp: {
    fontSize: 18,
    fontWeight: '500',
    color: '#333',
  },
  forecastMinMaxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  forecastMinMax: {
    fontSize: 12,
    color: '#666',
  },
  forecastRightColumn: {
    alignItems: 'flex-end',
  },
  forecastDescription: {
    fontSize: 14,
    color: '#666',
    textTransform: 'capitalize',
    marginBottom: 4,
  },
  forecastPrecipitation: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  forecastPrecipitationText: {
    fontSize: 12,
    color: '#1E90FF',
    marginLeft: 4,
  },
  hourlyDetailItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  hourlyDetailLeft: {
    width: '25%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  hourlyDetailTime: {
    marginRight: 8,
    fontSize: 14,
    color: '#333',
  },
  hourlyDetailCenter: {
    width: '40%',
  },
  hourlyDetailDescription: {
    fontSize: 14,
    color: '#666',
    textTransform: 'capitalize',
  },
  hourlyDetailRight: {
    width: '30%',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  hourlyDetailTemp: {
    fontSize: 16,
    fontWeight: '500',
    color: '#333',
    marginRight: 10,
  },
  hourlyDetailPrecip: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  hourlyDetailPrecipText: {
    fontSize: 12,
    color: '#1E90FF',
    marginLeft: 2,
  },
  showMoreButton: {
    paddingVertical: 12,
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#eee',
    marginTop: 10,
  },
  showMoreText: {
    fontSize: 16,
    color: '#0066cc',
    fontWeight: '500',
  },
  noDataContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  noDataText: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
  },
  // Tab styles
  tabContainer: {
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  tabBar: {
    height: 60,
    paddingBottom: 5,
    paddingTop: 5,
  },
  tabBarLabel: {
    fontSize: 12,
    textAlign: 'center',
    marginBottom: 4,
  },
  tabBarIcon: {
    marginTop: 4,
  },
  tabBarActive: {
    color: '#0066cc',
  },
  tabBarInactive: {
    color: '#888',
  },
  // Additional styles for WeatherContext and components
  forecastInfoText: {
    fontSize: 14,
    color: '#666',
    marginBottom: 10,
    lineHeight: 20,
  },
  additionalInfoContainer: {
    marginTop: 16,
  },
  detailsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 5,
  },
  detailLabel: {
    fontSize: 14,
    color: '#666',
  },
  detailValue: {
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
  },
  airQualityContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginTop: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  airQualityTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#333',
  },
  airQualityIndex: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    marginVertical: 5,
  },
  airQualityDescription: {
    fontSize: 16,
    color: '#666',
    marginBottom: 10,
  },
  divider: {
    height: 1,
    backgroundColor: '#eee',
    marginVertical: 10,
    width: '100%',
  },
  footerContainer: {
    marginTop: 20,
    alignItems: 'center',
    paddingBottom: 20,
  },
  footerText: {
    fontSize: 12,
    color: '#888',
    textAlign: 'center',
  },
  refreshContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
  },
  refreshText: {
    fontSize: 14,
    color: '#0066cc',
    marginLeft: 5,
  },
  lastUpdatedText: {
    fontSize: 12,
    color: '#888',
    textAlign: 'center',
    marginTop: 5,
  },
  settingsButton: {
    position: 'absolute',
    top: 10,
    right: 16,
    zIndex: 10,
  },
  unitToggleContainer: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 4,
    overflow: 'hidden',
    alignSelf: 'center',
    marginVertical: 10,
  },
  unitToggleButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unitToggleButtonActive: {
    backgroundColor: '#0066cc',
  },
  unitToggleText: {
    fontSize: 14,
    color: '#333',
  },
  unitToggleTextActive: {
    color: '#fff',
  },
  emptyStateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  emptyStateIcon: {
    marginBottom: 20,
    opacity: 0.7,
  },
  emptyStateText: {
    fontSize: 18,
    color: '#666',
    textAlign: 'center',
    marginBottom: 10,
  },
  emptyStateDescription: {
    fontSize: 14,
    color: '#888',
    textAlign: 'center',
    marginBottom: 20,
  },
  dailyForecastContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    alignItems: 'center',
  },
  dailyForecastList: {
    paddingVertical: 10,
  },
  dailyItem: {
    alignItems: 'center',
    marginHorizontal: 12,
    width: 100,
  },
  dailyDay: {
    fontSize: 14,
    color: '#333',
    marginBottom: 8,
  },
  dailyTempContainer: {
    alignItems: 'center',
    marginTop: 6,
  },
  dailyTemp: {
    fontSize: 16,
    fontWeight: '500',
    color: '#333',
    marginBottom: 4,
  },
  // Calendar styles
calendarContainer: {
  backgroundColor: '#fff',
  borderRadius: 12,
  padding: 15,
  marginBottom: 16,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 4,
  elevation: 3,
},
calendarHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  paddingVertical: 10,
  paddingHorizontal: 5,
  marginBottom: 10,
},
calendarMonthYear: {
  fontSize: 18,
  fontWeight: 'bold',
  color: '#333',
},
calendarNavButton: {
  padding: 8,
  borderRadius: 20,
  backgroundColor: '#f0f0f0',
},
calendarWeekdayHeader: {
  flexDirection: 'row',
  justifyContent: 'space-around',
  marginBottom: 10,
},
calendarWeekdayText: {
  width: '14.28%',
  textAlign: 'center',
  fontWeight: '500',
  color: '#666',
  fontSize: 14,
},
calendarGrid: {
  flexDirection: 'row',
  flexWrap: 'wrap',
},
calendarDay: {
  width: '14.28%',
  aspectRatio: 1,
  justifyContent: 'center',
  alignItems: 'center',
  marginBottom: 6,
  backgroundColor: '#E1F5FE',
  borderRadius: 8,
  padding: 4,
},
calendarToday: {
  backgroundColor: '#B3E5FC',
  borderWidth: 2,
  borderColor: '#0288D1',
},
calendarTodayText: {
  fontWeight: 'bold',
  color: '#0288D1',
},
calendarSelectedDay: {
  backgroundColor: '#0066cc',
  elevation: 2,
},
calendarSelectedDayText: {
  color: '#fff',
  fontWeight: 'bold',
},
calendarDayNoData: {
  backgroundColor: '#f5f5f5',
},
calendarEmptyDay: {
  width: '14.28%',
  aspectRatio: 1,
},
calendarDayText: {
  fontSize: 14,
  fontWeight: '500',
  color: '#333',
},
calendarDayTemp: {
  fontSize: 12,
  color: '#444',
  marginTop: 2,
},
calendarDayIcon: {
  marginTop: 2,
  opacity: 0.8,
},
calendarLegend: {
  flexDirection: 'row',
  justifyContent: 'center',
  marginTop: 16,
  marginBottom: 8,
},
legendItem: {
  flexDirection: 'row',
  alignItems: 'center',
  marginHorizontal: 8,
},
legendColorBox: {
  width: 12,
  height: 12,
  borderRadius: 3, 
  marginRight: 6,
},
legendText: {
  fontSize: 12,
  color: '#666',
},
selectedForecastContainer: {
  backgroundColor: '#fff',
  borderRadius: 12,
  padding: 20,
  marginBottom: 16,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 4,
  elevation: 3,
},
selectedForecastTitle: {
  fontSize: 18,
  fontWeight: 'bold',
  color: '#333',
  marginBottom: 15,
},
selectedForecastContent: {
  alignItems: 'stretch',
},
selectedForecastMainInfo: {
  flexDirection: 'row',
  alignItems: 'center',
  marginBottom: 20,
  paddingBottom: 15,
  borderBottomWidth: 1,
  borderBottomColor: '#eee',
},
selectedForecastTemp: {
  marginLeft: 15,
},
selectedForecastTempValue: {
  fontSize: 28,
  fontWeight: 'bold',
  color: '#333',
},
selectedForecastDescription: {
  fontSize: 16,
  color: '#666',
  textTransform: 'capitalize',
  marginTop: 5,
},
selectedForecastDetails: {
  marginTop: 5,
},
forecastDetailItem: {
  flexDirection: 'row',
  alignItems: 'center',
  marginBottom: 12,
},
forecastDetailLabel: {
  fontSize: 14,
  color: '#666',
  marginLeft: 10,
  width: 100,
},
forecastDetailValue: {
  fontSize: 14,
  fontWeight: '500',
  color: '#333',
}
});